version: '3.9'

services:
  db:
    image: postgres:14-alpine
    container_name: kingsystem_db
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - kingsystem_db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready -U ${DB_USERNAME} ${DB_DATABASE}" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  kingsystem_db:
    external: true